### ISSUE TITLE
site bug: two luca

### ISSUE THREAD

**Issue by jihoonjh34** [ShinyColorsDB/ShinyColorsDB-DataSite#4]
![chrome_RTTvZOqkaw](https://github.com/ShinyColorsDB/ShinyColorsDB-DataSite/assets/46193810/39efc38b-b0c8-4809-b4a8-97646f4f668e)

**Comment by alex94539** [comment]
caused by backend sql :((

https://github.com/ShinyColorsDB/ShinyColorsDB-ApiServer/blob/main/src/info/info.service.ts#L77
and here
https://github.com/ShinyColorsDB/ShinyColorsDB-ApiServer/blob/main/src/info/info.service.ts#L83

![image](https://github.com/ShinyColorsDB/ShinyColorsDB-DataSite/assets/31380333/cf1d5364-1052-4369-945d-5d01824f5f98)

and these two records. Since these two cards has same release date, sqls above will dump them both.
And honestly, I have no idea how to fix this and I have no time to research sql recently, so I'll put it right here for now.
(Any help is welcomed)
